# Generated by Django 5.1.5 on 2025-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.BigIntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('processed_by', models.IntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
