# Generated by Django 5.1.5 on 2025-03-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received')], max_length=1000, verbose_name='Notification Type'),
        ),
    ]
