# Generated by Django 5.1.5 on 2025-04-24 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sports.location'),
            preserve_default=False,
        ),
    ]
