# Generated by Django 5.1.5 on 2025-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_confirmation_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['sport']},
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='submitted_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings_booking',
        ),
    ]
