# Generated by Django 5.1.5 on 2025-03-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='condition',
            new_name='condition_of_kit',
        ),
    ]
