# Generated by Django 5.1.5 on 2025-04-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_balance_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
